---
- name: create user "app" and home dir will /opt/app and its a /bin/nologin
  user:
    name: app
    comment: app
    home: /opt/app
    shell: /bin/nologin
    state: present

- name: crete group app
  group: 
    name: app
    state: present

- name: Create a app directory if it does not exist
  file:
    path: /opt/app/tomcat
    state: directory
    mode: '0755'
    owner: app
    group: app

- name: Download tomcat tar.gz file from internet
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz
    dest: /opt
    mode: '0440'

- name: Unarchive tomcat tar file that is already on the remote machine
  unarchive:
    src: /opt/apache-tomcat-8.5.72.tar.gz
    dest: /opt/app/tomcat
    remote_src: yes

- name: Recursively change ownership of a directory
  file:
    path: /opt/app
    state: directory
    recurse: yes
    owner: app
    group: app


- name: copy tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: /opt/app/tomcat/apache-tomcat-8.5.72/conf/tomcat-users.xml
    owner: app
    group: app
    mode: '0644'
  notify: restart tomcat

- name: copy context.xml
  template:
    src: context.xml.j2
    dest: /opt/app/tomcat/apache-tomcat-8.5.72/webapps/manager/META-INF/context.xml
    owner: app
    group: app
    mode: '0644'
  notify: restart tomcat

- name: copy tomcat service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0755'
  notify: restart tomcat


- name: Start and enable tomcat service
  service:
    name: tomcat
    state: started
    enabled: yes



