---
- name: Install apache webserver
  apt:
    name: apache2
    state: present
- name: Copy file with owner and permissions
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: yes
