---
- name: Apache webserver
  hosts: web
  become: yes
  become_method: sudo
  tasks:
    - name: Install apache webserver
      yum:
        name: httpd
        state: present
    - name: Copy file with owner and permissions
      copy:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        remote_src: no
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes



